%% CLEAR VARIABLES
clc
clear all
close all

%% LOAD DATA FROM DATASET
% add directories to Matlab search path
addpath('Dataset', 'Dataset_Norway', 'Filters', 'Plots', 'SetupAndConfiguration');

% Dataset available:	
%		DAS4Whale
%		DAS4Tracking
%		Norway
%		OOI_Wilcock
% Dataset filenames:
%		DAS4Whale
%			- "20200627_052441_ch10001_to_ch15000_whale_raw_L160s.mat"
%		DAS4Tracking
%			- "20220822_114507_to_114837_ch9803_to_ch24509_sample_Freq_78_Hz.mat"
%			- "20220822_122707_to_123037_ch9803_to_ch24509_sample_Freq_78_Hz.mat"
%			- "20220906_165106_to_165436_ch2450_to_ch9191_sample_Freq_125_Hz.mat"
%			- "20220906_175106_to_175436_ch2450_to_ch9191_sample_Freq_125_Hz_outer.mat"
%			- "20220906_175107_to_175437_ch2450_to_ch9191_sample_Freq_125_Hz_inner.mat"
%		Norway
%			- "122403.hdf5"
%		OOI_Wilcock
%			- "North-C2-HF-P1kHz-GL30m-Sp2m-FS500Hz_2021-11-03T015731Z.h5"

dataset_name	= 'DAS4Whale';
DAS				= feval(str2func(dataset_name + "_cfg"));
data			= DAS.load_data("20200627_052441_ch10001_to_ch15000_whale_raw_L160s.mat");

export_plot		= false;
% -----------------------------------------------------------------------%

%% BUTTERWORTH BANDPASS FILTER
% parameters
bp = DAS.bandpass();

% apply filter
strain_filtered = butterworth_bp_filter( ...
	data.strain, ...
	bp.cutoff_freq, ...
	bp.order, ...
	data.sampling_frequency_Hz);

% clear variables
clear bp
% -----------------------------------------------------------------------%

%% MEDIAN FILTER 2D (3X3 SYMMETRIC)
% parameters
medFilt = DAS.medFilt();

% apply filter
strain_filtered = median_filter_2D( ...
	strain_filtered, ...
	medFilt.dim);

% clear variables
clear medFilt
% -----------------------------------------------------------------------%

%% FK FILTERING
% parameters
fkFilt = DAS.fkFilt();

% design fk filter
fk_filter =	fk_filter_design( ...
	data.dimensions, ...
	data.channel_distance_m, ...
	data.sampling_interval_s);

% apply fk filter
strain_filtered = fk_filter_filt( ...
	strain_filtered, ...
	fk_filter);

% clear variables
clear fkFilt fk_filter
% -----------------------------------------------------------------------%

%% TIME-SPACE PLOT
% parameters
tx = DAS.tx_plot();

% time-space plot
time_space_plot = get_time_space_plot( ...
	strain_filtered, ...
	data.time, ...
	data.distance_m, ...
	'subtitle', data.time_and_date, ...
    'time_lim', tx.time_lim, ...
	'distance_lim', tx.distance_lim, ...
	'strain_lim', tx.strain_lim, ...
	'norm', true);

hold on;

% position of interest markers
yline(tx.cpa_m, '--', 'CPA','LineWidth', 1, 'Color', '#FFD1DF');
yline(tx.channel_position_m, '--', 'far from CPA', 'LineWidth', 1, 'Color', '#D1FFBD');

% draw propagation speed lines on time-space plot
speedline = false;
if speedline
	draw_prop_speed_lines( ...
		data.time, ...
		data.propagation_speed, ...
		tx.p1);
end

draw_lines = false;
if draw_lines
	p1 = [122.45 43184.7];
	p2 = [129.24 49504.5];
	p3 = [122.5 42208.3];
	p4 = [128.62 36178.5];
	draw_lines_tx_plot(p1, p2, p3, p4);
end

hold off

if export_plot
	% export plot as png
	exportgraphics( ...
		time_space_plot, ...
		fullfile(dataset_name, ['time_space_plot_' dataset_name  '.png']));
end
% clear variables
clear tx speedline time_space_plot draw_lines p1 p2 p3 p4
% -----------------------------------------------------------------------%

%% STRAIN WAVEFORM (SINGLE CHANNEL)
% parameters
wf = DAS.waveform();
% to use strain with matched filtering (Trondheim dataset):
% strain_filt_no_match = strain_filtered;
% strain_filtered = strain_matched_filtered;

% plot strain waveform channel of interest
strain_waveform = get_strain_waveform( ...
	strain_filtered, ...
	data.distance_m, ...
	data.time, ...
	wf.channel_position_m, ...
	wf.filename_audio, ...
	data.sampling_frequency_Hz, ...
	'subtitle', data.time_and_date, ...
	'time_lim', wf.time_lim, ...
	'strain_lim', wf.strain_lim);

if export_plot
	% export plot as png
	exportgraphics( ...
		strain_waveform, ...
		fullfile(dataset_name, ['strain_waveform_' dataset_name  '.png']));
end

% clear variables
clear wf strain_waveform
% -----------------------------------------------------------------------%

%% SPECTROGRAM (SINGLE CHANNEL)
% parameters
sg = DAS.spectrogram();
% to use strain with matched filtering (Trondheim dataset):
% strain_filt_no_match = strain_filtered;
% strain_filtered = strain_matched_filtered;

% plot spectrogram
spectrogram_plot = get_spectrogram( ...
	strain_filtered, ...
	data.distance_m, ...
	data.sampling_frequency_Hz, ...
	sg.channel_position_m, ...
	sg.nfft, ...
	sg.window_len, ...
	sg.window, ...
	sg.overlap_pct, ...
	'subtitle', data.time_and_date, ...
	'time_lim', sg.time_lim, ...
	'frequency_lim', sg.frequency_lim, ...
	'strain_lim', sg.strain_lim, ...
	'norm', true);

if export_plot
	% export plot as png
	exportgraphics( ...
		spectrogram_plot, ...
		fullfile(dataset_name, ['spectrogram_' dataset_name  '.png']));
end

% clear variables
clear sg spectrogram_plot
% -----------------------------------------------------------------------%

%% SPACE-FREQUENCY PLOT
% parameters
fx = DAS.fx_plot();

% plot spatio-spectral representation
space_frequency_plot = get_space_frequency_plot( ...
	strain_filtered, ...
	data.distance_m, ...
	data.sampling_frequency_Hz, ...
	fx.nfft, ...
	fx.time_window, ...
	fx.time_interval, ...
	fx.filename_animation, ...
	'subtitle', data.time_and_date, ...
	'frequency_lim', fx.frequency_lim, ...
	'strain_lim', fx.strain_lim, ...
	'get_animation', true);

if export_plot
	% export plot as png
	exportgraphics( ...
		space_frequency_plot, ...
		fullfile(dataset_name, ['fx_plot_' dataset_name  '.png']));
end

% clear variables
clear fx space_frequency_plot
% -----------------------------------------------------------------------%

%% CROSS-CORRELATION STATISTICS
% parameters
xcorr = DAS.correlation();
% to use strain with matched filtering (Trondheim dataset):
% strain_filt_no_match = strain_filtered;
% strain_filtered = strain_matched_filtered;

% plot correlogram
correlogram = get_correlogram( ...
	strain_filtered, ...
	data.sampling_frequency_Hz, ...
	data.distance_m, ...
    xcorr.channel_position_m, ...
	xcorr.offset_m, ...
	xcorr.time_lag, ...
	xcorr.time_interval, ...
	'subtitle', data.time_and_date, ...
	'use_hilbert',false);

if export_plot
	% export plot as png
	exportgraphics( ...
		correlogram, ...
		fullfile(dataset_name, ['correlogram_' dataset_name  '.png']));
end

% plot correlation statistics and export data to csv file
[correlation_statistics, xcorr_plot] = get_correlation_statistics( ...
	strain_filtered, ...
	data.sampling_frequency_Hz, ...
	data.distance_m, ...
	data.channel_distance_m, ...
	xcorr.channel_position_m, ...
	xcorr.offset_m, ...
	xcorr.time_lag, ...
	xcorr.time_interval, ...
	xcorr.filename_table, ...
	'subtitle', data.time_and_date, ...
	'offset_step', 2, ...
	'use_hilbert', false);

if export_plot
	% export plot as png
	exportgraphics( ...
		xcorr_plot, ...
		fullfile(dataset_name, ['cross_corr_stats_' dataset_name  '.png']));
end

% clear variables
clear xcorr correlogram correlation_statistics xcorr_plot
% -----------------------------------------------------------------------%