%% CLEAR VARIABLES
clc
clear all
close all
clearAllMemoizedCaches

%% LOAD DATA FROM DATASET
% add directories to Matlab search path
addpath('Dataset', 'Dataset_Norway', 'Filters', 'Plots', 'SetupAndConfiguration');

% Dataset available:	
%		DAS4Whale
%		DAS4Tracking
%		Norway
%		OOI_Wilcock
% Dataset filenames:
%		DAS4Whale
%			- "20200627_052441_ch10001_to_ch15000_whale_raw_L160s.mat"
%			- "20200716_154302_ch21001_to_ch22000_whale_raw_L720s.mat"
%			- "20200716_154302_ch22001_to_ch23000_whale_raw_L720s.mat"
%		DAS4Tracking
%			- "20220822_114507_to_114837_ch9803_to_ch24509_sample_Freq_78_Hz.mat"
%			- "20220822_122707_to_123037_ch9803_to_ch24509_sample_Freq_78_Hz.mat"
%			- "20220906_165106_to_165436_ch2450_to_ch9191_sample_Freq_125_Hz.mat"
%			- "20220906_175106_to_175436_ch2450_to_ch9191_sample_Freq_125_Hz_outer.mat"
%			- "20220906_175107_to_175437_ch2450_to_ch9191_sample_Freq_125_Hz_inner.mat"
%		Norway
%			- "122403.hdf5"
%		OOI_Wilcock
%			- "North-C2-HF-P1kHz-GL30m-Sp2m-FS500Hz_2021-11-03T015731Z.h5"
%			- "North-C1-LR-P1kHz-GL50m-Sp2m-FS200Hz_2021-11-04T020002Z.h5"

dataset_name	= 'DAS4Whale';
DAS				= feval(str2func(dataset_name + "_cfg"));
data			= DAS.load_data("20200627_052441_ch10001_to_ch15000_whale_raw_L160s.mat");

export_plot		= false;
% -----------------------------------------------------------------------%

%% BUTTERWORTH BANDPASS FILTER
% parameters
bp = DAS.bandpass();

% apply filter
strain_filtered = butterworth_bp_filter( ...
	data.strain, ...
	bp.cutoff_freq, ...
	bp.order, ...
	data.sampling_frequency_Hz);

% clear variables
clear bp
% -----------------------------------------------------------------------%

%% MEDIAN FILTER 2D (3X3 SYMMETRIC)
% parameters
medFilt = DAS.medFilt();

% apply filter
strain_filtered = median_filter_2D( ...
	strain_filtered, ...
	medFilt.dim);

% clear variables
clear medFilt
% -----------------------------------------------------------------------%

%% FK FILTERING
% parameters
fkFilt = DAS.fkFilt();

% fkFilt_c_range = [1400 1450 2000 2050];

% design fk filter
fk_filter =	fk_filter_design( ...
	data.dimensions, ...
	data.channel_distance_m, ...
	data.sampling_interval_s, ...
    'c_range', fkFilt.c_range);

% apply fk filter
strain_filtered = fk_filter_filt( ...
	strain_filtered, ...
	fk_filter);

plot_fk_spectrum = false;

if plot_fk_spectrum
    fk_spectrum( ...
        data.strain, ...
        data.channel_distance_m, ...
        data.sampling_interval_s, ...
        'subtitle', [data.time_and_date, "no filters"], ...
        'dB_lim', [-120 0])
end

if plot_fk_spectrum
    fk_spectrum( ...
        strain_filtered, ...
        data.channel_distance_m, ...
        data.sampling_interval_s, ...
        'subtitle', [data.time_and_date, "bandpass + fk filter"], ...
        'dB_lim', [-120 0])
end

% clear variables
clear fkFilt fk_filter plot_fk_spectrum
% -----------------------------------------------------------------------%

%% TIME-SPACE PLOT
% parameters
tx = DAS.tx_plot();

% tx_time_lim = [];
% tx_distance_lim = [15700 58900];
% tx_strain_lim = [-130 -100];

% time-space plot
time_space_plot = get_time_space_plot( ...
	strain_filtered, ...
	data.time, ...
	data.distance_m, ...
    'subtitle', data.time_and_date, ...
    'time_lim', tx.time_lim, ...
    'distance_lim', tx.distance_lim, ...
    'strain_lim', tx.strain_lim, ...
	'norm', true);

% % time-space plot
% time_space_plot = get_time_space_plot( ...
% 	strain_filtered, ...
% 	data.time, ...
% 	data.distance_m, ...
% 	'subtitle', data.time_and_date, ...
%   'time_lim', tx_time_lim, ...
% 	'distance_lim', tx_distance_lim, ...
% 	'strain_lim', tx_strain_lim, ...
% 	'norm', true);

hold on;

% position of interest markers
%yline(tx.cpa_m, '--', 'CPA','LineWidth', 1, 'Color', '#FFD1DF');
%yline(tx.channel_position_m, '--', 'far from CPA', 'LineWidth', 1, 'Color', '#D1FFBD');

% draw propagation speed lines on time-space plot
speedline = false;
if speedline
	draw_prop_speed_lines( ...
		data.time, ...
		data.propagation_speed, ...
		tx.p1);
end

% draw lines following triangle shape to find CPA
CPA_lines = true;
if CPA_lines
    p1 = [122 43331.7];
    p2 = [128.08 49463.6];
    p3 = [122.114 41918.2];
    p4 = [127.373 36599.3];
	draw_lines_tx_plot(p1, p2, p3, p4)
end

hold off

if export_plot
	% export plot as png
	exportgraphics( ...
		time_space_plot, ...
		fullfile(dataset_name, ['time_space_plot_' dataset_name  '.png']));
end
% clear variables
clear tx speedline time_space_plot draw_lines p1 p2 p3 p4
% -----------------------------------------------------------------------%

%% STRAIN WAVEFORM (SINGLE CHANNEL)
% parameters
wf = DAS.waveform();
% to use strain with matched filtering (Trondheim dataset):
% strain_filt_no_match = strain_filtered;
% strain_filtered = strain_matched_filtered;

% wf_filename_audio = 'audio_waveform.wav';
% wf_channel_position_m = 87450;

% plot strain waveform channel of interest
strain_waveform = get_strain_waveform( ...
	strain_filtered, ...
	data.distance_m, ...
	data.time, ...
	wf.channel_position_m, ...
	wf.filename_audio, ...
	data.sampling_frequency_Hz, ...
	'subtitle', data.time_and_date, ...
	'time_lim', wf.time_lim, ...
	'strain_lim', wf.strain_lim);

if export_plot
	% export plot as png
	exportgraphics( ...
		strain_waveform, ...
		fullfile(dataset_name, ['strain_waveform_' dataset_name  '.png']));
end

% clear variables
clear wf strain_waveform
% -----------------------------------------------------------------------%

%% SPECTROGRAM (SINGLE CHANNEL)
% parameters
sg = DAS.spectrogram();
% to use strain with matched filtering (Trondheim dataset):
% strain_filt_no_match = strain_filtered;
% strain_filtered = strain_matched_filtered;

% plot spectrogram
spectrogram_plot = get_spectrogram( ...
	strain_filtered, ...
	data.distance_m, ...
	data.sampling_frequency_Hz, ...
	sg.channel_position_m, ...
	sg.nfft, ...
	sg.window_len, ...
	sg.window, ...
	sg.overlap_pct, ...
	'subtitle', data.time_and_date, ...
	'time_lim', sg.time_lim, ...
	'frequency_lim', sg.frequency_lim, ...
	'strain_lim', sg.strain_lim, ...
	'norm', true);

if export_plot
	% export plot as png
	exportgraphics( ...
		spectrogram_plot, ...
		fullfile(dataset_name, ['spectrogram_' dataset_name  '.png']));
end

% clear variables
clear sg spectrogram_plot
% -----------------------------------------------------------------------%

%% SPACE-FREQUENCY PLOT
% parameters
fx = DAS.fx_plot();

% plot spatio-spectral representation
space_frequency_plot = get_space_frequency_plot( ...
	strain_filtered, ...
	data.distance_m, ...
	data.sampling_frequency_Hz, ...
	fx.nfft, ...
	fx.time_window, ...
	fx.time_interval, ...
	fx.filename_animation, ...
	'subtitle', data.time_and_date, ...
	'frequency_lim', fx.frequency_lim, ...
	'strain_lim', fx.strain_lim, ...
	'get_animation', true);

if export_plot
	% export plot as png
	exportgraphics( ...
		space_frequency_plot, ...
		fullfile(dataset_name, ['fx_plot_' dataset_name  '.png']));
end

% clear variables
clear fx space_frequency_plot
% -----------------------------------------------------------------------%

%% CROSS-CORRELATION STATISTICS
% parameters
xcorr = DAS.correlation();
% to use strain with matched filtering (Trondheim dataset):
% strain_filt_no_match = strain_filtered;
% strain_filtered = strain_matched_filtered;

% plot correlogram
correlogram = get_correlogram( ...
	strain_filtered, ...
	data.sampling_frequency_Hz, ...
	data.distance_m, ...
    xcorr.channel_position_m, ...
	xcorr.offset_m, ...
	xcorr.time_lag, ...
	xcorr.time_interval, ...
	'subtitle', data.time_and_date, ...
	'use_hilbert',false);

if export_plot
	% export plot as png
	exportgraphics( ...
		correlogram, ...
		fullfile(dataset_name, ['correlogram_' dataset_name  '.png']));
end

% plot correlation statistics and export data to csv file
[correlation_statistics, xcorr_plot] = get_correlation_statistics( ...
	strain_filtered, ...
	data.sampling_frequency_Hz, ...
	data.distance_m, ...
	data.channel_distance_m, ...
	xcorr.channel_position_m, ...
	xcorr.offset_m, ...
	xcorr.time_lag, ...
	xcorr.time_interval, ...
	xcorr.filename_table, ...
	'subtitle', data.time_and_date, ...
	'offset_step', 2, ...
	'use_hilbert', false);

if export_plot
	% export plot as png
	exportgraphics( ...
		xcorr_plot, ...
		fullfile(dataset_name, ['cross_corr_stats_' dataset_name  '.png']));
end

% clear variables
clear xcorr correlogram correlation_statistics xcorr_plot
% -----------------------------------------------------------------------%


%% PLOT CABLE DEPTH
cable_depth = -data.cable_depth;
channel_ref = 44000;
[~, idx_ref] = min(abs(data.distance_m - channel_ref));

offset = 300;
[~, idx_offset_pos] = min(abs(data.distance_m - (channel_ref + offset)));
[~, idx_offset_neg] = min(abs(data.distance_m - (channel_ref - offset)));

CPA = 42680;
[~, idx_CPA] = min(abs(data.distance_m - CPA));

x_axis = 1:5000;
%x_axis = x_axis * data.channel_distance_m;

figure;
plot(x_axis, cable_depth);
hold on
plot(x_axis(idx_ref), cable_depth(idx_ref), 'r.', 'MarkerSize', 20);
plot(x_axis(idx_offset_pos), cable_depth(idx_offset_pos), 'g.', 'MarkerSize', 20);
plot(x_axis(idx_offset_neg), cable_depth(idx_offset_neg), 'b.', 'MarkerSize', 20);
plot(x_axis(idx_CPA), cable_depth(idx_CPA), 'y.', 'MarkerSize', 20);

legend('cable', 'reference channel', 'positive offset', 'negative offset', 'CPA');